# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: ec_mongo
    networks:
      - general_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb

  mongo-express:
    image: mongo-express
    container_name: ec_mongo_express
    restart: always
    ports:
      - 8081:8081
    networks:
      - general_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: express
      ME_CONFIG_MONGODB_ADMINPASSWORD: express
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:mongodb@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  kong_migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    container_name: ec_kong_migration
    networks:
      - kong_network
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
    links:
      - kong_db
    depends_on:
      - kong_db

  kong:
    image: kong:latest
    container_name: ec_kong
    networks:
      kong_network:
      general_network:
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_LISTEN_SSL: "0.0.0.0:8444"
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
      - "8444:8444"
    #dns:
    #  - 192.168.1.10:8600
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 2s
      retries: 15
    depends_on:
      - kong_db
      - kong_migration

  kong_db:
    image: postgres:16.3
    container_name: ec_kong_db
    shm_size: 64mb
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass
      POSTGRES_DB: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      kong_network:
      general_network:
    ports:
      - "9989:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  kong_network:
    driver: bridge

  general_network:
    driver: bridge

volumes:
  kong_data:
